In this section, we're going to see how we're going to be working with numpy as a Python library

 ================  Importing numpy

In [16]:
import numpy as np

Creating an array in Numpy

In [17]:
a = np.array([1,2,3,4])

print(a[0])
print(a[3])
print(a[1:])
print(a[:2])


# You are creating a list based on the elements you add separated by a comma
a[0],a[3]

1
4
[2 3 4]
[1 2]


(1, 4)

Dimensions and Shapes

In [18]:
# Creating a matrix
b = np.array([[1,2,3,4],[5,6,7,8]])

# Getting the shape of the matrix ( Rows and Columns )
b.shape

# How many dimensions does It have ?
b.ndim


2

Statisitical Operations on Matrices

In [20]:
# Getting the sum of the matrix
b.sum()

# Getting the mean of the matrix ( moyenne )
b.mean()

# Getting the sum of each column
# FIrst row
b.sum(axis=0)
# Second row
b.sum(axis=1)

array([10, 26])

In [21]:
A = np.array([
    ['a', 'b', 'c'],
    ['d', 'e', 'f'],
    ['g', 'h', 'i']
])

print(A[:, :2])

[['a' 'b']
 ['d' 'e']
 ['g' 'h']]


Arranging a matrix 

In [27]:
# Creating a new matrix ranfing from 0 to 4 with 5 elements
c = np.arange(2,7)
print(c)

[2 3 4 5 6]
